
library(shiny)
require(shinydashboard)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(plotly)





# Reading Each continent's country data
Asia <- read.csv("Asia.csv",header=F)$V1
Africa <- read.csv("Africa.csv",header=F)$V1
Ocenia <- read.csv("Ocenia.csv",header=F)$V1
North_America <- read.csv("North America.csv",header=F)$V1
South_America <- read.csv("South America.csv",header=F)$V1
Europe <- read.csv("Europe.csv",header=F)$V1


## app.R ##
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
  
)
#Dashboard header carrying the title of the dashboard
header <- dashboardHeader(title = "Basic Dashboard")  

#Sidebar content of the dashboard
sidebar <- dashboardSidebar(
  sidebarMenu(
    selectInput("state", "Choose a state:",
                list(  'Asia' = Asia,
                      'Europe' = Europe,
                     'Africa' = Africa,
                     'North America' = North_America,
                     'South America' = South_America,
                     'Oceania' = Ocenia
                     
                     ),
                selected = "India"
                )
    
    
  )
)

frow1 <- fluidRow(
  valueBoxOutput("value1")
  ,valueBoxOutput("value2")
  ,valueBoxOutput("value3")
  
)

# combine the two fluid rows to make the body
body <- dashboardBody(frow1)

#completing the ui part with dashboardPage
ui <- dashboardPage(title = 'This is my Page title', header, sidebar, body, skin='red')
##########################################################################################
##########################################################################################

# create the server functions for the dashboard  
  server <- function(input, output,session) { 
    country <- reactive(
      {input$state}
    )
  
  data <- read.csv('covid-data.csv',stringsAsFactors = F,header=T)
  
  
  observeEvent(input$state, {
    
    
    
    d = data %>% filter(location == input$state) 
    #print(d)
    time_series <- c(select(d,date))
    #view(time_series)
    total_cases <- sum(d$new_cases,na.rm = TRUE)
    total_deaths <- sum(d$new_deaths,na.rm = TRUE)
    total_tests <- sum(d$new_tests,na.rm = TRUE)
    
    #time_series$date <- as.Date(time_series, "%m/%d/%Y")
    #time_series[order(time_series$date),]
    #print(time_series)
    
    cases <- data.frame(time_series,d$new_cases) %>% mutate(id = row_number())
    deaths <- data.frame(time_series,d$new_deaths) %>% mutate(id = row_number())
    tests <- data.frame(time_series,d$new_tests) %>% mutate(id = row_number())
    tests[is.na(tests)] <- 0
    deaths[is.na(deaths)] <- 0
    cases[is.na(cases)] <- 0
    
    # This function is important for making the data to be used in animations generated by Plotly
    accumulate_by <- function(dat, var) {
      var <- lazyeval::f_eval(var, dat) 
      lvls <- plotly:::getLevels(var) 
      dats <- lapply(seq_along(lvls), 
                     function(x) {
                       cbind.data.frame(dat[var %in% lvls[seq(1, x)], ],
                                        frame = lvls[[x]])}) 
      dplyr::bind_rows(dats)}
    
    AllData <- list(cases,tests,deaths) %>% reduce(left_join, by = "id")
    frames <- AllData %>% accumulate_by (~id)
    print(frames)
###################################################################################################################    
#    # This function is important for making the data to be used in animations generated by Plotly
#    # METHOD 1 (Animated graphs using ggplotly() after making ggplot()): Now we will generate a combined plot by ggplot for all cases and their time series in region mentioned above
#    
#    fig2 <- plot_ly() %>%  
#      
#      # We are going to add the information of Confirmed cases by using add_trace()
#          add_trace(data=frames, 
#                x = ~time_series, 
#                y = ~d.new_cases, 
#                name= 'Confirmed', 
#                frame = ~frame,  
#                type = 'scatter', 
#                mode = 'lines+markers', 
#                marker = list(size = 10, 
#                              color = 'rgba(51, 153, 255, .5)', 
#                              line = list(color = 'rgba(0, 38, 77, .8)', width = 2)), 
#                line = list(color = 'rgba(0, 38, 77, .8)', 
#                            width = 2)) %>% 
#      
#      # We are going to add the information of Recovered cases by using add_trace()
#      add_trace(data=frames, 
#                x = ~time_series, 
#                y = ~d.new_tests, 
#                name='Recovered', 
#                frame = ~frame,  
#                type = 'scatter', 
#                mode = 'lines+markers', 
#                marker = list(size = 10, 
#                              color = 'rgba(153, 255, 153, .8)', 
#                              line = list(color = 'rgba(0, 179, 0, .8)', width = 2)), 
#                line = list(color = 'rgba(0, 179, 0, .8)', 
#                            width = 2)) %>% 
#      
#      # We are going to add the information of Deaths by using add_trace()
#      add_trace(data=frames, 
#                x = ~time_series, 
#                y = ~d.new_deaths, 
#                name='Deaths', 
#                frame = ~frame, 
#                type = 'scatter', 
#                mode = 'lines+markers',
#                marker = list(size = 10, 
#                              color = 'rgba(255, 102, 102, .5)', 
#                              line = list(color = 'rgba(152, 0, 0, .8)', width = 2)), 
#                line = list(color = 'rgba(152, 0, 0, 1)', 
#                            width = 2)) %>% 
#      # Formating the layout of the graph
#      layout(legend=list(x = 100, y = 0.5, yanchor="top"), 
#             title = list(text=paste("<b> Cases Over the Period of Time in India", "Since First Report </b>"), 
#                          size = 10), 
#             xaxis=list(autoscale=FALSE,
#                        range = c(head(frames$Date, n=1),tail(frames$time_series, n=1)+2),
#                        title = "<b> Days </b>"), 
#             yaxis=list(title = "<b> Cases </b>")) %>%
#      
      # Animation options
#      animation_opts(10, easing = "elastic", redraw = TRUE)
#    
#    # Plot the fig2
#    fig2
###################################################################################################################    
    output$value1 <- renderValueBox({
      valueBox(
        formatC(total_cases, format="d", big.mark=',')
        ,paste('Total Cases',input$state)
        ,icon = icon("user-friends",lib='font-awesome')
        ,color = "purple")  
    })
    output$value2 <- renderValueBox({ 
      valueBox(
        formatC(total_deaths, format="d", big.mark=',')
        ,'Total Deaths'
        ,icon = icon("ambulance",lib='font-awesome')
        ,color = "green")  
    })
    output$value3 <- renderValueBox({
      valueBox(
        formatC(total_tests, format="d", big.mark=',')
        ,paste('Total Tests')
        ,icon = icon("notes-medical",lib='font-awesome')
        ,color = "yellow")   
    })
  })
  
  
  
  
}
shinyApp(ui, server)

